client_client:
    resource: "@ClientBundle/Resources/config/routing/client.yml"
    prefix:   /administration/member

client_homepage:
    path:     /
    defaults: { _controller: ClientBundle:Default:index }
