memberGestion:
    path:     /all
    defaults: { _controller: AdministrationBundle:Member/Member:index }

redacteurGestion:
    path:     /redacteurGestion
    defaults: { _controller: AdministrationBundle:Member/Redacteur:index }

memberProfile:
    path:     /profile/{id}
    defaults: { _controller: AdministrationBundle:Member/MemberProfile:profile }

memberNouveau:
    path:     /nouveau
    defaults: { _controller: AdministrationBundle:Member/MemberNouveau:nouveau }
